name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.KEY }}

      - name: Add VPS to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 2.57.241.58 >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          ssh root@2.57.241.58 "
            cd /var/www/project &&
            git pull origin main &&
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh 
            npm install --legacy-peer-deps &&
            cd frontend &&
            npm install --legacy-peer-deps &&
            NODE_OPTIONS='--max-old-space-size=2048' npm run build &&
            sudo -i -u postgres psql -c "DROP DATABASE IF EXISTS users;" &&
            sudo -i -u postgres psql -c "CREATE DATABASE users;" &&
            sudo -i -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE users TO overlord;" &&
            sudo -i -u postgres psql -c "ALTER DATABASE users OWNER TO overlord;" &&
            cd ../backend &&
            npx sequelize-cli db:migrate &&
            npx sequelize-cli db:seed:all &&
            pm2 restart server &&
            systemctl restart nginx"
